### ISSUE TITLE
The publisher's certificate could not be verified

### ISSUE THREAD

**Issue by MrrNekos** [celestiamobile/CelestiaUWP#28]
![Bez tytułu](https://github.com/celestiamobile/CelestiaUWP/assets/71604619/438abb9c-1689-48a5-91ed-e0cb3d667223)

The publisher's certificate could not be verified

**Comment by levinli303** [comment]
If you are side loading, do not open the .msix directly. Instead run the script Install.ps1

**Comment by MrrNekos** [comment]
thanks
